spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/collector_camel_poc


scheduler-routes:
  collector:
    id: CollectorSchedulerRoute
    cron-expression: 0/5 * * ? * * *
    thread-pool: 10